# ==============================================================================
# Base Application Configuration
# ==============================================================================
spring.application.name=food-delivery-backend

<<<<<<< HEAD
# Active Profile (prod active by default)
spring.profiles.active=prod
=======
# Local Database Connection Details (Localhost on Linux)
#spring.datasource.url=jdbc:postgresql://localhost:5432/fooddelivery04
#spring.datasource.username=postgres
#spring.datasource.password=postgres


spring.datasource.driver-class-name=org.postgresql.Driver
>>>>>>> cc194a352dc672d4029200f787984d243e4df495

# Actuator & Prometheus Metrics Exposure for Monitoring (Grafana / Prometheus)
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true